Deploy presentation
KUBAHO3/Sharing-World pull request #4
Opened 2023-03-15 17:19 UTC by KUBAHO3

In this project:

- I have fixed all linter errors
- I have added a loom walkthrough video to give a tour of the project
- added all content of the program and speakers dynamically from an array
- Documented well the project through readme file

2023-03-15 20:15 UTC, OyePriscilla requested changes
Hi @KUBAHO3 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Demonstrate ability to t use CSS media query ✔️ 
Use GitHub Pages to deploy web pages ✔️ 
Use JavaScript to manipulate DOM elements ✔️ 
Use JavaScript events ✔️ 
Use objects to store and access data ✔️ 

## Required Changes ♻️

**- [ ] Please kindly take note that you supposed to have worked on one feature branch (correct GitHub Flow) but you created five branches which suppose not to be. One of the senior CRs (@Abimbola) instructed me to review your work because if I invalidate it you will have to open a new repository and start all over. Please carefully take note of the comments I will drop in this summary template, I can't use the Github inline comment feature perfectly because you've merged most your code.** ℹ️ 

- [x] In index.js line 107, kindly use the `article` element instead of `div` according to best practises. The `article` tag specifies independent and self-contained content. **Kindly apply the same to the speakers section as well (line 65).**
- [x] Remove the console.log statement in index.js line 63, this can create security loop hole to your app. ℹ️ 
- [x] Please kindly give appropriate credit to the author ([Cindy Shin in Behance](https://www.behance.net/adagio07).) in the acknowledgement section of your README file. 👍 

- [x] According to the project requirement, kindly show a piece of code that you are proud of in your video presentation.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 20:15 UTC, OyePriscilla commented on index.html
> +    <link rel="icon" href="images/icon_head.jpg" type="image/icon">
Kindly take note of the suggested changes below:
1. In line 29, kindly change the `header` tag to `nav` tag according to best practises. 👍 This is applicable to your about.html file also (line 29)
2. Line 62 supposed to be a `h1` tag because `h1` should points specifically at the title of the page. 👍 
3. The original fonts stated in behance design are cocogoose and lato, kindly import it appropriately. 👍 
4. Kindly increase the left and right padding of `body` of your app so that we can have a design that is close to the given template.

## Your Design 
<img width="955" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/225427852-f75e0204-95a3-4e42-abdb-6b1551a87468.png">


## Behance Design
<img width="623" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/225427110-a09aabdd-00d9-4dad-ad0c-a2ec6a3d5818.png">

@KUBAHO3 Please take note of this as well
 **- [ ] I observed that your design pattern for the` partner` section is different from what we have in behance design, kindly implement this for the homepage.**
**- [ ] More so, your background-color for the `footer` in about page is different from what we have in the given template. 👍**

2023-03-15 20:15 UTC, OyePriscilla commented on styles.css
> +
- [ ] Kindly remove the commented code that we have in line 5 - line 10 of your styles.css according to best practises. 👍

2023-03-16 14:48 UTC, KUBAHO3 commented
About the paddings, You can refer to the bellow screenshot of how it looks in the bigger screen

The design
![cindy design](https://user-images.githubusercontent.com/88271934/225653443-f8c30039-ad67-432f-9dee-081ea31d98bb.png)

My design:
![my design](https://user-images.githubusercontent.com/88271934/225653773-adcb7d14-cdd9-42ae-b011-5d60c37362f2.png)

The wider the screen the wider the paddings

2023-03-16 15:23 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @KUBAHO3 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 15:23 UTC, bobb-Rob commented on about.html
>      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
- [x] As mentioned by the previous reviewer, the footer section in the about page has a dark color as seen in the Behance design template. Kindly use the appropriate color. 
- [x] [OPTIONAL] In the about page, the partners' section is not visible. See your design image below and notice the portion I marked with red X. _I labeled this comment as optional because it was not mesntioned by the previous reviewer, but I strongly recommend that you fix this._

Behance design 
--- |
![image](https://user-images.githubusercontent.com/84156714/225659928-ee685dbd-c865-4e49-a323-c405179103e7.png) 

Your design
--- |
![image](https://user-images.githubusercontent.com/84156714/225660513-26948523-41c4-4d9c-977a-6c4c0bf642ed.png)

2023-03-16 15:23 UTC, bobb-Rob commented on index.html
> -                <h2 class="hero-title">BLACK PANTHER <br> MOVIE LAUNCH <br> 2022</h2>
- [x] As mentioned by the previous reviewer,  your design pattern for the partner section is different from what we have in Behance design, kindly implement the correct thing in the main pages. _**Note that the partner section should not be visible on the about page.**_

2023-03-16 16:42 UTC, KUBAHO3 commented on about.html
>      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
Fixed and thank you

2023-03-16 19:21 UTC, mckent05 approved these changes
Hi @KUBAHO3, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Your capstone looks good, you have done well 👍 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 20:21 UTC, merged